### PR TITLE
Added code to deploy DLR, Edge and configure OSPF for same

### PR DESCRIPTION
**Pull request by rchopkar**
1. Added code to deploy DLR, Edge and configure OSPF

### CODE REVIEW

**Comment by rchopkar** [comment]
Hi Yves,
I have closed previous pull request and created this new pull request. Please let me know what the next step I need to do.

**Comment by rchopkar** [comment]
I also added pull request for nsxraml repository.

**Comment by yfauser** [comment]
Don't know why this doesn't close automatically. But I have the code in 'devel', so let's see if I get into any trouble when merging into master later.

Thanks!

**Comment by rchopkar** [comment]
Hi Yves,

I have added code to configure load balancer for VCD and PSC. I found differences in the configuration steps for PSC and VCD, hence I've created two separate files.If this is not acceptable, suggest how to to merge these changes into a single file.

Thanks,
Rakesh

**Comment by yfauser** [comment]
@rchopkar Can you please test the new ESG, DLR, OSPF and Redist Code and see if it implements everything you need? Please then send a new pull request only including the new Load Balancer Code you want me to merge in. Thanks!

**Pull request closed without merging**
